/**
 * Full Hyperliquid universe as listed on E8 Markets Terminal.
 * Snapshot 2026-09-04 from api.hyperliquid.xyz
 * info/meta + HIP-3 perpDexs. Native delisted names omitted.
 * Display ticker is the HIP-3 suffix (xyz:SP500 → SP500).
 */

export type HlAssetClass = "crypto" | "index" | "fx" | "metal" | "energy" | "equity";

export type HlAsset = {
  symbol: string;
  hl: string;
  dex: string;
  venue: string;
  assetClass: HlAssetClass;
  maxLeverage: number;
};

export const HL_UNIVERSE: readonly HlAsset[] = [
  { symbol: "BTC", hl: "BTC", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 40 },
  { symbol: "ETH", hl: "ETH", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 25 },
  { symbol: "ATOM", hl: "ATOM", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "DYDX", hl: "DYDX", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "SOL", hl: "SOL", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 20 },
  { symbol: "AVAX", hl: "AVAX", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "BNB", hl: "BNB", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "APE", hl: "APE", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "OP", hl: "OP", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "LTC", hl: "LTC", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "ARB", hl: "ARB", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "DOGE", hl: "DOGE", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "INJ", hl: "INJ", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "SUI", hl: "SUI", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "kPEPE", hl: "kPEPE", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "CRV", hl: "CRV", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "LDO", hl: "LDO", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "LINK", hl: "LINK", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "STX", hl: "STX", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "CFX", hl: "CFX", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "GMX", hl: "GMX", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "SNX", hl: "SNX", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "XRP", hl: "XRP", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 20 },
  { symbol: "BCH", hl: "BCH", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "APT", hl: "APT", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "AAVE", hl: "AAVE", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "COMP", hl: "COMP", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "WLD", hl: "WLD", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "YGG", hl: "YGG", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "TRX", hl: "TRX", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "kSHIB", hl: "kSHIB", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "UNI", hl: "UNI", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "SEI", hl: "SEI", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "RUNE", hl: "RUNE", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "ZRO", hl: "ZRO", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "DOT", hl: "DOT", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "BANANA", hl: "BANANA", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "TRB", hl: "TRB", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "BIGTIME", hl: "BIGTIME", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "KAS", hl: "KAS", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "BLUR", hl: "BLUR", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "TIA", hl: "TIA", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "BSV", hl: "BSV", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "ADA", hl: "ADA", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "MINA", hl: "MINA", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "POLYX", hl: "POLYX", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "GAS", hl: "GAS", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "PENDLE", hl: "PENDLE", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "FET", hl: "FET", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "NEAR", hl: "NEAR", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "MEME", hl: "MEME", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "ORDI", hl: "ORDI", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "NEO", hl: "NEO", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "ZEN", hl: "ZEN", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "FIL", hl: "FIL", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "PYTH", hl: "PYTH", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "SUSHI", hl: "SUSHI", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "IMX", hl: "IMX", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "kBONK", hl: "kBONK", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "GMT", hl: "GMT", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "SUPER", hl: "SUPER", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "JUP", hl: "JUP", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "kLUNC", hl: "kLUNC", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "RSR", hl: "RSR", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "GALA", hl: "GALA", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "JTO", hl: "JTO", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "ACE", hl: "ACE", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "WIF", hl: "WIF", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "CAKE", hl: "CAKE", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "PEOPLE", hl: "PEOPLE", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "ENS", hl: "ENS", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "ETC", hl: "ETC", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "XAI", hl: "XAI", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "MANTA", hl: "MANTA", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "UMA", hl: "UMA", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "ONDO", hl: "ONDO", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "ALT", hl: "ALT", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "ZETA", hl: "ZETA", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "DYM", hl: "DYM", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "W", hl: "W", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "STRK", hl: "STRK", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "TAO", hl: "TAO", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "AR", hl: "AR", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "kFLOKI", hl: "kFLOKI", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "BOME", hl: "BOME", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "ETHFI", hl: "ETHFI", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "ENA", hl: "ENA", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "MNT", hl: "MNT", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "TNSR", hl: "TNSR", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "SAGA", hl: "SAGA", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "MERL", hl: "MERL", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "HBAR", hl: "HBAR", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "POPCAT", hl: "POPCAT", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "EIGEN", hl: "EIGEN", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "REZ", hl: "REZ", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "NOT", hl: "NOT", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "TURBO", hl: "TURBO", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "BRETT", hl: "BRETT", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "IO", hl: "IO", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "ZK", hl: "ZK", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "RENDER", hl: "RENDER", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "POL", hl: "POL", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "CELO", hl: "CELO", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "HMSTR", hl: "HMSTR", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "kNEIRO", hl: "kNEIRO", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "GOAT", hl: "GOAT", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "MOODENG", hl: "MOODENG", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "GRASS", hl: "GRASS", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "PURR", hl: "PURR", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "PNUT", hl: "PNUT", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "XLM", hl: "XLM", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "SAND", hl: "SAND", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "IOTA", hl: "IOTA", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "ALGO", hl: "ALGO", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "HYPE", hl: "HYPE", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "ME", hl: "ME", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "MOVE", hl: "MOVE", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "VIRTUAL", hl: "VIRTUAL", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "PENGU", hl: "PENGU", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "USUAL", hl: "USUAL", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "FARTCOIN", hl: "FARTCOIN", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "AIXBT", hl: "AIXBT", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "BIO", hl: "BIO", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "GRIFFAIN", hl: "GRIFFAIN", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "SPX", hl: "SPX", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "S", hl: "S", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "MORPHO", hl: "MORPHO", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "TRUMP", hl: "TRUMP", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "MELANIA", hl: "MELANIA", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "ANIME", hl: "ANIME", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "VVV", hl: "VVV", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "BERA", hl: "BERA", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "LAYER", hl: "LAYER", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "KAITO", hl: "KAITO", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "NIL", hl: "NIL", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "PAXG", hl: "PAXG", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "BABY", hl: "BABY", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "WCT", hl: "WCT", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "HYPER", hl: "HYPER", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "ZORA", hl: "ZORA", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "INIT", hl: "INIT", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "NXPC", hl: "NXPC", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "SOPH", hl: "SOPH", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "RESOLV", hl: "RESOLV", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "SYRUP", hl: "SYRUP", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "PUMP", hl: "PUMP", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "PROVE", hl: "PROVE", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "XPL", hl: "XPL", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "WLFI", hl: "WLFI", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "LINEA", hl: "LINEA", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "SKY", hl: "SKY", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "ASTER", hl: "ASTER", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "AVNT", hl: "AVNT", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "STBL", hl: "STBL", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "0G", hl: "0G", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "HEMI", hl: "HEMI", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "APEX", hl: "APEX", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "2Z", hl: "2Z", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "ZEC", hl: "ZEC", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "MON", hl: "MON", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "MET", hl: "MET", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "MEGA", hl: "MEGA", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "CC", hl: "CC", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "ICP", hl: "ICP", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "AERO", hl: "AERO", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "STABLE", hl: "STABLE", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "FOGO", hl: "FOGO", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "LIT", hl: "LIT", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "XMR", hl: "XMR", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "AXS", hl: "AXS", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "DASH", hl: "DASH", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "SKR", hl: "SKR", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "AZTEC", hl: "AZTEC", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "CHIP", hl: "CHIP", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "GRAM", hl: "GRAM", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "CASHCAT", hl: "CASHCAT", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "PONS", hl: "PONS", dex: "native", venue: "Hyperliquid", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "XYZ100", hl: "xyz:XYZ100", dex: "xyz", venue: "XYZ", assetClass: "index", maxLeverage: 30 },
  { symbol: "TSLA", hl: "xyz:TSLA", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 20 },
  { symbol: "NVDA", hl: "xyz:NVDA", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 20 },
  { symbol: "GOLD", hl: "xyz:GOLD", dex: "xyz", venue: "XYZ", assetClass: "metal", maxLeverage: 25 },
  { symbol: "HOOD", hl: "xyz:HOOD", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "INTC", hl: "xyz:INTC", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "PLTR", hl: "xyz:PLTR", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "COIN", hl: "xyz:COIN", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "META", hl: "xyz:META", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 20 },
  { symbol: "AAPL", hl: "xyz:AAPL", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 20 },
  { symbol: "MSFT", hl: "xyz:MSFT", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 20 },
  { symbol: "ORCL", hl: "xyz:ORCL", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "GOOGL", hl: "xyz:GOOGL", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 20 },
  { symbol: "AMZN", hl: "xyz:AMZN", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 20 },
  { symbol: "AMD", hl: "xyz:AMD", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "MU", hl: "xyz:MU", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "SNDK", hl: "xyz:SNDK", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "MSTR", hl: "xyz:MSTR", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "CRCL", hl: "xyz:CRCL", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "NFLX", hl: "xyz:NFLX", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "COST", hl: "xyz:COST", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 20 },
  { symbol: "LLY", hl: "xyz:LLY", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "SKHX", hl: "xyz:SKHX", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "TSM", hl: "xyz:TSM", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "JPY", hl: "xyz:JPY", dex: "xyz", venue: "XYZ", assetClass: "fx", maxLeverage: 50 },
  { symbol: "EUR", hl: "xyz:EUR", dex: "xyz", venue: "XYZ", assetClass: "fx", maxLeverage: 50 },
  { symbol: "SILVER", hl: "xyz:SILVER", dex: "xyz", venue: "XYZ", assetClass: "metal", maxLeverage: 25 },
  { symbol: "RIVN", hl: "xyz:RIVN", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "BABA", hl: "xyz:BABA", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "CL", hl: "xyz:CL", dex: "xyz", venue: "XYZ", assetClass: "energy", maxLeverage: 20 },
  { symbol: "COPPER", hl: "xyz:COPPER", dex: "xyz", venue: "XYZ", assetClass: "metal", maxLeverage: 20 },
  { symbol: "NATGAS", hl: "xyz:NATGAS", dex: "xyz", venue: "XYZ", assetClass: "energy", maxLeverage: 10 },
  { symbol: "URANIUM", hl: "xyz:URANIUM", dex: "xyz", venue: "XYZ", assetClass: "energy", maxLeverage: 10 },
  { symbol: "ALUMINIUM", hl: "xyz:ALUMINIUM", dex: "xyz", venue: "XYZ", assetClass: "metal", maxLeverage: 20 },
  { symbol: "SMSN", hl: "xyz:SMSN", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "PLATINUM", hl: "xyz:PLATINUM", dex: "xyz", venue: "XYZ", assetClass: "metal", maxLeverage: 20 },
  { symbol: "USAR", hl: "xyz:USAR", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "CRWV", hl: "xyz:CRWV", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "URNM", hl: "xyz:URNM", dex: "xyz", venue: "XYZ", assetClass: "energy", maxLeverage: 10 },
  { symbol: "PALLADIUM", hl: "xyz:PALLADIUM", dex: "xyz", venue: "XYZ", assetClass: "metal", maxLeverage: 20 },
  { symbol: "DXY", hl: "xyz:DXY", dex: "xyz", venue: "XYZ", assetClass: "index", maxLeverage: 20 },
  { symbol: "GME", hl: "xyz:GME", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "KR200", hl: "xyz:KR200", dex: "xyz", venue: "XYZ", assetClass: "index", maxLeverage: 20 },
  { symbol: "SOFTBANK", hl: "xyz:SOFTBANK", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "JP225", hl: "xyz:JP225", dex: "xyz", venue: "XYZ", assetClass: "index", maxLeverage: 20 },
  { symbol: "HYUNDAI", hl: "xyz:HYUNDAI", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "KIOXIA", hl: "xyz:KIOXIA", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "EWY", hl: "xyz:EWY", dex: "xyz", venue: "XYZ", assetClass: "index", maxLeverage: 20 },
  { symbol: "EWJ", hl: "xyz:EWJ", dex: "xyz", venue: "XYZ", assetClass: "index", maxLeverage: 20 },
  { symbol: "BRENTOIL", hl: "xyz:BRENTOIL", dex: "xyz", venue: "XYZ", assetClass: "energy", maxLeverage: 20 },
  { symbol: "VIX", hl: "xyz:VIX", dex: "xyz", venue: "XYZ", assetClass: "index", maxLeverage: 3 },
  { symbol: "HIMS", hl: "xyz:HIMS", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "SP500", hl: "xyz:SP500", dex: "xyz", venue: "XYZ", assetClass: "index", maxLeverage: 50 },
  { symbol: "DKNG", hl: "xyz:DKNG", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "LITE", hl: "xyz:LITE", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "CORN", hl: "xyz:CORN", dex: "xyz", venue: "XYZ", assetClass: "energy", maxLeverage: 20 },
  { symbol: "XLE", hl: "xyz:XLE", dex: "xyz", venue: "XYZ", assetClass: "index", maxLeverage: 20 },
  { symbol: "WHEAT", hl: "xyz:WHEAT", dex: "xyz", venue: "XYZ", assetClass: "energy", maxLeverage: 20 },
  { symbol: "TTF", hl: "xyz:TTF", dex: "xyz", venue: "XYZ", assetClass: "energy", maxLeverage: 20 },
  { symbol: "BX", hl: "xyz:BX", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "PURRDAT", hl: "xyz:PURRDAT", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "MRVL", hl: "xyz:MRVL", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "RKLB", hl: "xyz:RKLB", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "BIRD", hl: "xyz:BIRD", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "VOL", hl: "xyz:VOL", dex: "xyz", venue: "XYZ", assetClass: "index", maxLeverage: 10 },
  { symbol: "DRAM", hl: "xyz:DRAM", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 20 },
  { symbol: "CBRS", hl: "xyz:CBRS", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "EWZ", hl: "xyz:EWZ", dex: "xyz", venue: "XYZ", assetClass: "index", maxLeverage: 20 },
  { symbol: "KRW", hl: "xyz:KRW", dex: "xyz", venue: "XYZ", assetClass: "fx", maxLeverage: 50 },
  { symbol: "ZM", hl: "xyz:ZM", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "EBAY", hl: "xyz:EBAY", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "H100", hl: "xyz:H100", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "NIFTY", hl: "xyz:NIFTY", dex: "xyz", venue: "XYZ", assetClass: "index", maxLeverage: 20 },
  { symbol: "ARM", hl: "xyz:ARM", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "EWT", hl: "xyz:EWT", dex: "xyz", venue: "XYZ", assetClass: "index", maxLeverage: 20 },
  { symbol: "GBP", hl: "xyz:GBP", dex: "xyz", venue: "XYZ", assetClass: "fx", maxLeverage: 50 },
  { symbol: "SPCX", hl: "xyz:SPCX", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 20 },
  { symbol: "IBOV", hl: "xyz:IBOV", dex: "xyz", venue: "XYZ", assetClass: "index", maxLeverage: 20 },
  { symbol: "ASML", hl: "xyz:ASML", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "MINIMAX", hl: "xyz:MINIMAX", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "BB", hl: "xyz:BB", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "QNT", hl: "xyz:QNT", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "DELL", hl: "xyz:DELL", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "IBM", hl: "xyz:IBM", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "AVGO", hl: "xyz:AVGO", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "NOW", hl: "xyz:NOW", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "NBIS", hl: "xyz:NBIS", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "WDC", hl: "xyz:WDC", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "NOK", hl: "xyz:NOK", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "SMH", hl: "xyz:SMH", dex: "xyz", venue: "XYZ", assetClass: "index", maxLeverage: 20 },
  { symbol: "BE", hl: "xyz:BE", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "ZHIPU", hl: "xyz:ZHIPU", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "QCOM", hl: "xyz:QCOM", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "STRC", hl: "xyz:STRC", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "BOT", hl: "xyz:BOT", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "AMAT", hl: "xyz:AMAT", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "IBIDEN", hl: "xyz:IBIDEN", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "GIGADEV", hl: "xyz:GIGADEV", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "SHAZ", hl: "xyz:SHAZ", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "SKHY", hl: "xyz:SKHY", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "KSTR", hl: "xyz:KSTR", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "CXMT", hl: "xyz:CXMT", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "GEV", hl: "xyz:GEV", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "KORU", hl: "xyz:KORU", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "UNITREE", hl: "xyz:UNITREE", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "LYTE", hl: "xyz:LYTE", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "NCLD", hl: "xyz:NCLD", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "SOXL", hl: "xyz:SOXL", dex: "xyz", venue: "XYZ", assetClass: "index", maxLeverage: 10 },
  { symbol: "MAGS", hl: "xyz:MAGS", dex: "xyz", venue: "XYZ", assetClass: "index", maxLeverage: 10 },
  { symbol: "IREN", hl: "xyz:IREN", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "NET", hl: "xyz:NET", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "CRWD", hl: "xyz:CRWD", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "RDDT", hl: "xyz:RDDT", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "AAOI", hl: "xyz:AAOI", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "MRNA", hl: "xyz:MRNA", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "XBI", hl: "xyz:XBI", dex: "xyz", venue: "XYZ", assetClass: "index", maxLeverage: 10 },
  { symbol: "SHEIN", hl: "xyz:SHEIN", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "YMTC", hl: "xyz:YMTC", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 5 },
  { symbol: "BMNR", hl: "xyz:BMNR", dex: "xyz", venue: "XYZ", assetClass: "equity", maxLeverage: 10 },
  { symbol: "TSLA", hl: "flx:TSLA", dex: "flx", venue: "Felix Exchange", assetClass: "equity", maxLeverage: 10 },
  { symbol: "NVDA", hl: "flx:NVDA", dex: "flx", venue: "Felix Exchange", assetClass: "equity", maxLeverage: 10 },
  { symbol: "CRCL", hl: "flx:CRCL", dex: "flx", venue: "Felix Exchange", assetClass: "equity", maxLeverage: 5 },
  { symbol: "COIN", hl: "flx:COIN", dex: "flx", venue: "Felix Exchange", assetClass: "equity", maxLeverage: 10 },
  { symbol: "XMR", hl: "flx:XMR", dex: "flx", venue: "Felix Exchange", assetClass: "equity", maxLeverage: 10 },
  { symbol: "GOLD", hl: "flx:GOLD", dex: "flx", venue: "Felix Exchange", assetClass: "metal", maxLeverage: 25 },
  { symbol: "SILVER", hl: "flx:SILVER", dex: "flx", venue: "Felix Exchange", assetClass: "metal", maxLeverage: 25 },
  { symbol: "OIL", hl: "flx:OIL", dex: "flx", venue: "Felix Exchange", assetClass: "energy", maxLeverage: 15 },
  { symbol: "GAS", hl: "flx:GAS", dex: "flx", venue: "Felix Exchange", assetClass: "equity", maxLeverage: 5 },
  { symbol: "BTC", hl: "flx:BTC", dex: "flx", venue: "Felix Exchange", assetClass: "equity", maxLeverage: 1 },
  { symbol: "COPPER", hl: "flx:COPPER", dex: "flx", venue: "Felix Exchange", assetClass: "metal", maxLeverage: 20 },
  { symbol: "PALLADIUM", hl: "flx:PALLADIUM", dex: "flx", venue: "Felix Exchange", assetClass: "metal", maxLeverage: 25 },
  { symbol: "PLATINUM", hl: "flx:PLATINUM", dex: "flx", venue: "Felix Exchange", assetClass: "metal", maxLeverage: 25 },
  { symbol: "USDE", hl: "flx:USDE", dex: "flx", venue: "Felix Exchange", assetClass: "equity", maxLeverage: 20 },
  { symbol: "USA500", hl: "flx:USA500", dex: "flx", venue: "Felix Exchange", assetClass: "index", maxLeverage: 30 },
  { symbol: "USA100", hl: "flx:USA100", dex: "flx", venue: "Felix Exchange", assetClass: "equity", maxLeverage: 30 },
  { symbol: "SPACEX", hl: "vntl:SPACEX", dex: "vntl", venue: "Ventuals", assetClass: "equity", maxLeverage: 3 },
  { symbol: "OPENAI", hl: "vntl:OPENAI", dex: "vntl", venue: "Ventuals", assetClass: "equity", maxLeverage: 3 },
  { symbol: "ANTHROPIC", hl: "vntl:ANTHROPIC", dex: "vntl", venue: "Ventuals", assetClass: "equity", maxLeverage: 3 },
  { symbol: "MAG7", hl: "vntl:MAG7", dex: "vntl", venue: "Ventuals", assetClass: "index", maxLeverage: 20 },
  { symbol: "SEMIS", hl: "vntl:SEMIS", dex: "vntl", venue: "Ventuals", assetClass: "index", maxLeverage: 20 },
  { symbol: "ROBOT", hl: "vntl:ROBOT", dex: "vntl", venue: "Ventuals", assetClass: "equity", maxLeverage: 20 },
  { symbol: "INFOTECH", hl: "vntl:INFOTECH", dex: "vntl", venue: "Ventuals", assetClass: "equity", maxLeverage: 20 },
  { symbol: "NUCLEAR", hl: "vntl:NUCLEAR", dex: "vntl", venue: "Ventuals", assetClass: "equity", maxLeverage: 20 },
  { symbol: "DEFENSE", hl: "vntl:DEFENSE", dex: "vntl", venue: "Ventuals", assetClass: "equity", maxLeverage: 20 },
  { symbol: "ENERGY", hl: "vntl:ENERGY", dex: "vntl", venue: "Ventuals", assetClass: "equity", maxLeverage: 20 },
  { symbol: "BIOTECH", hl: "vntl:BIOTECH", dex: "vntl", venue: "Ventuals", assetClass: "equity", maxLeverage: 20 },
  { symbol: "GOLDJM", hl: "vntl:GOLDJM", dex: "vntl", venue: "Ventuals", assetClass: "equity", maxLeverage: 20 },
  { symbol: "SILVERJM", hl: "vntl:SILVERJM", dex: "vntl", venue: "Ventuals", assetClass: "equity", maxLeverage: 20 },
  { symbol: "WHEAT", hl: "vntl:WHEAT", dex: "vntl", venue: "Ventuals", assetClass: "energy", maxLeverage: 10 },
  { symbol: "SOY", hl: "vntl:SOY", dex: "vntl", venue: "Ventuals", assetClass: "equity", maxLeverage: 10 },
  { symbol: "BTC", hl: "hyna:BTC", dex: "hyna", venue: "HyENA", assetClass: "crypto", maxLeverage: 40 },
  { symbol: "ETH", hl: "hyna:ETH", dex: "hyna", venue: "HyENA", assetClass: "crypto", maxLeverage: 25 },
  { symbol: "HYPE", hl: "hyna:HYPE", dex: "hyna", venue: "HyENA", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "SOL", hl: "hyna:SOL", dex: "hyna", venue: "HyENA", assetClass: "crypto", maxLeverage: 20 },
  { symbol: "LIT", hl: "hyna:LIT", dex: "hyna", venue: "HyENA", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "ZEC", hl: "hyna:ZEC", dex: "hyna", venue: "HyENA", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "XRP", hl: "hyna:XRP", dex: "hyna", venue: "HyENA", assetClass: "crypto", maxLeverage: 20 },
  { symbol: "LIGHTER", hl: "hyna:LIGHTER", dex: "hyna", venue: "HyENA", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "BNB", hl: "hyna:BNB", dex: "hyna", venue: "HyENA", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "DOGE", hl: "hyna:DOGE", dex: "hyna", venue: "HyENA", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "SUI", hl: "hyna:SUI", dex: "hyna", venue: "HyENA", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "PUMP", hl: "hyna:PUMP", dex: "hyna", venue: "HyENA", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "FARTCOIN", hl: "hyna:FARTCOIN", dex: "hyna", venue: "HyENA", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "ENA", hl: "hyna:ENA", dex: "hyna", venue: "HyENA", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "XMR", hl: "hyna:XMR", dex: "hyna", venue: "HyENA", assetClass: "crypto", maxLeverage: 5 },
  { symbol: "LTC", hl: "hyna:LTC", dex: "hyna", venue: "HyENA", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "LINK", hl: "hyna:LINK", dex: "hyna", venue: "HyENA", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "XPL", hl: "hyna:XPL", dex: "hyna", venue: "HyENA", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "IP", hl: "hyna:IP", dex: "hyna", venue: "HyENA", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "BCH", hl: "hyna:BCH", dex: "hyna", venue: "HyENA", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "ADA", hl: "hyna:ADA", dex: "hyna", venue: "HyENA", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "1000PEPE", hl: "hyna:1000PEPE", dex: "hyna", venue: "HyENA", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "SILVER", hl: "hyna:SILVER", dex: "hyna", venue: "HyENA", assetClass: "metal", maxLeverage: 25 },
  { symbol: "GOLD", hl: "hyna:GOLD", dex: "hyna", venue: "HyENA", assetClass: "metal", maxLeverage: 25 },
  { symbol: "BASED", hl: "hyna:BASED", dex: "hyna", venue: "HyENA", assetClass: "crypto", maxLeverage: 3 },
  { symbol: "US500", hl: "km:US500", dex: "km", venue: "Markets by Kinetiq", assetClass: "index", maxLeverage: 25 },
  { symbol: "BABA", hl: "km:BABA", dex: "km", venue: "Markets by Kinetiq", assetClass: "equity", maxLeverage: 10 },
  { symbol: "EUR", hl: "km:EUR", dex: "km", venue: "Markets by Kinetiq", assetClass: "fx", maxLeverage: 50 },
  { symbol: "USBOND", hl: "km:USBOND", dex: "km", venue: "Markets by Kinetiq", assetClass: "energy", maxLeverage: 10 },
  { symbol: "SMALL2000", hl: "km:SMALL2000", dex: "km", venue: "Markets by Kinetiq", assetClass: "index", maxLeverage: 20 },
  { symbol: "USTECH", hl: "km:USTECH", dex: "km", venue: "Markets by Kinetiq", assetClass: "index", maxLeverage: 25 },
  { symbol: "USENERGY", hl: "km:USENERGY", dex: "km", venue: "Markets by Kinetiq", assetClass: "index", maxLeverage: 15 },
  { symbol: "USOIL", hl: "km:USOIL", dex: "km", venue: "Markets by Kinetiq", assetClass: "energy", maxLeverage: 10 },
  { symbol: "TSLA", hl: "km:TSLA", dex: "km", venue: "Markets by Kinetiq", assetClass: "equity", maxLeverage: 12 },
  { symbol: "SILVER", hl: "km:SILVER", dex: "km", venue: "Markets by Kinetiq", assetClass: "metal", maxLeverage: 20 },
  { symbol: "GOLD", hl: "km:GOLD", dex: "km", venue: "Markets by Kinetiq", assetClass: "metal", maxLeverage: 25 },
  { symbol: "AAPL", hl: "km:AAPL", dex: "km", venue: "Markets by Kinetiq", assetClass: "equity", maxLeverage: 15 },
  { symbol: "GOOGL", hl: "km:GOOGL", dex: "km", venue: "Markets by Kinetiq", assetClass: "equity", maxLeverage: 15 },
  { symbol: "SEMI", hl: "km:SEMI", dex: "km", venue: "Markets by Kinetiq", assetClass: "equity", maxLeverage: 15 },
  { symbol: "GLDMINE", hl: "km:GLDMINE", dex: "km", venue: "Markets by Kinetiq", assetClass: "equity", maxLeverage: 10 },
  { symbol: "NVDA", hl: "km:NVDA", dex: "km", venue: "Markets by Kinetiq", assetClass: "equity", maxLeverage: 12 },
  { symbol: "TENCENT", hl: "km:TENCENT", dex: "km", venue: "Markets by Kinetiq", assetClass: "equity", maxLeverage: 10 },
  { symbol: "JPN225", hl: "km:JPN225", dex: "km", venue: "Markets by Kinetiq", assetClass: "equity", maxLeverage: 25 },
  { symbol: "MU", hl: "km:MU", dex: "km", venue: "Markets by Kinetiq", assetClass: "equity", maxLeverage: 10 },
  { symbol: "PLTR", hl: "km:PLTR", dex: "km", venue: "Markets by Kinetiq", assetClass: "equity", maxLeverage: 12 },
  { symbol: "XIAOMI", hl: "km:XIAOMI", dex: "km", venue: "Markets by Kinetiq", assetClass: "equity", maxLeverage: 10 },
  { symbol: "BMNR", hl: "km:BMNR", dex: "km", venue: "Markets by Kinetiq", assetClass: "equity", maxLeverage: 10 },
  { symbol: "RTX", hl: "km:RTX", dex: "km", venue: "Markets by Kinetiq", assetClass: "equity", maxLeverage: 10 },
  { symbol: "USA500", hl: "abcd:USA500", dex: "abcd", venue: "ABCDEx", assetClass: "index", maxLeverage: 25 },
  { symbol: "USA500", hl: "cash:USA500", dex: "cash", venue: "dreamcash", assetClass: "index", maxLeverage: 20 },
  { symbol: "TSLA", hl: "cash:TSLA", dex: "cash", venue: "dreamcash", assetClass: "equity", maxLeverage: 20 },
  { symbol: "NVDA", hl: "cash:NVDA", dex: "cash", venue: "dreamcash", assetClass: "equity", maxLeverage: 20 },
  { symbol: "HOOD", hl: "cash:HOOD", dex: "cash", venue: "dreamcash", assetClass: "equity", maxLeverage: 20 },
  { symbol: "GOOGL", hl: "cash:GOOGL", dex: "cash", venue: "dreamcash", assetClass: "equity", maxLeverage: 20 },
  { symbol: "INTC", hl: "cash:INTC", dex: "cash", venue: "dreamcash", assetClass: "equity", maxLeverage: 20 },
  { symbol: "AMZN", hl: "cash:AMZN", dex: "cash", venue: "dreamcash", assetClass: "equity", maxLeverage: 20 },
  { symbol: "MSFT", hl: "cash:MSFT", dex: "cash", venue: "dreamcash", assetClass: "equity", maxLeverage: 20 },
  { symbol: "META", hl: "cash:META", dex: "cash", venue: "dreamcash", assetClass: "equity", maxLeverage: 20 },
  { symbol: "GOLD", hl: "cash:GOLD", dex: "cash", venue: "dreamcash", assetClass: "metal", maxLeverage: 20 },
  { symbol: "SILVER", hl: "cash:SILVER", dex: "cash", venue: "dreamcash", assetClass: "metal", maxLeverage: 20 },
  { symbol: "EWY", hl: "cash:EWY", dex: "cash", venue: "dreamcash", assetClass: "index", maxLeverage: 20 },
  { symbol: "WTI", hl: "cash:WTI", dex: "cash", venue: "dreamcash", assetClass: "equity", maxLeverage: 10 },
  { symbol: "BTC", hl: "cash:BTC", dex: "cash", venue: "dreamcash", assetClass: "equity", maxLeverage: 40 },
  { symbol: "KWEB", hl: "cash:KWEB", dex: "cash", venue: "dreamcash", assetClass: "equity", maxLeverage: 20 },
  { symbol: "ETH", hl: "cash:ETH", dex: "cash", venue: "dreamcash", assetClass: "equity", maxLeverage: 40 },
  { symbol: "CAR", hl: "cash:CAR", dex: "cash", venue: "dreamcash", assetClass: "equity", maxLeverage: 10 },
  { symbol: "TOTAL2", hl: "para:TOTAL2", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 20 },
  { symbol: "OTHERS", hl: "para:OTHERS", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "BTCD", hl: "para:BTCD", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 20 },
  { symbol: "H100", hl: "para:H100", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "AVGO", hl: "para:AVGO", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "COHR", hl: "para:COHR", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "GLW", hl: "para:GLW", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "CRDO", hl: "para:CRDO", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "LRCX", hl: "para:LRCX", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "NET", hl: "para:NET", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "STX", hl: "para:STX", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "IREN", hl: "para:IREN", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "VST", hl: "para:VST", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "TER", hl: "para:TER", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "AAOI", hl: "para:AAOI", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "10Y", hl: "para:10Y", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 20 },
  { symbol: "CIEN", hl: "para:CIEN", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "NAVER", hl: "para:NAVER", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "RDDT", hl: "para:RDDT", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "UNITREE", hl: "para:UNITREE", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "CRWD", hl: "para:CRWD", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "TENCENT", hl: "para:TENCENT", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "CAMBRICON", hl: "para:CAMBRICON", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "MELI", hl: "para:MELI", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "SMCI", hl: "para:SMCI", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "ANSEM", hl: "para:ANSEM", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 3 },
  { symbol: "INNOLIGHT", hl: "para:INNOLIGHT", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "30Y", hl: "para:30Y", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 20 },
  { symbol: "2Y", hl: "para:2Y", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 20 },
  { symbol: "IGV", hl: "para:IGV", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "SOFI", hl: "para:SOFI", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "ANTH", hl: "para:ANTH", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 5 },
  { symbol: "TTWO", hl: "para:TTWO", dex: "para", venue: "Paragon", assetClass: "equity", maxLeverage: 10 },
  { symbol: "US500", hl: "mkts:US500", dex: "mkts", venue: "Markets By Kinetiq", assetClass: "index", maxLeverage: 25 },
  { symbol: "BABA", hl: "mkts:BABA", dex: "mkts", venue: "Markets By Kinetiq", assetClass: "equity", maxLeverage: 10 },
  { symbol: "EUR", hl: "mkts:EUR", dex: "mkts", venue: "Markets By Kinetiq", assetClass: "fx", maxLeverage: 50 },
  { symbol: "USBOND", hl: "mkts:USBOND", dex: "mkts", venue: "Markets By Kinetiq", assetClass: "energy", maxLeverage: 10 },
  { symbol: "SMALL2000", hl: "mkts:SMALL2000", dex: "mkts", venue: "Markets By Kinetiq", assetClass: "index", maxLeverage: 20 },
  { symbol: "USTECH", hl: "mkts:USTECH", dex: "mkts", venue: "Markets By Kinetiq", assetClass: "index", maxLeverage: 25 },
  { symbol: "USENERGY", hl: "mkts:USENERGY", dex: "mkts", venue: "Markets By Kinetiq", assetClass: "index", maxLeverage: 15 },
  { symbol: "USOIL", hl: "mkts:USOIL", dex: "mkts", venue: "Markets By Kinetiq", assetClass: "energy", maxLeverage: 10 },
  { symbol: "TSLA", hl: "mkts:TSLA", dex: "mkts", venue: "Markets By Kinetiq", assetClass: "equity", maxLeverage: 12 },
  { symbol: "SILVER", hl: "mkts:SILVER", dex: "mkts", venue: "Markets By Kinetiq", assetClass: "metal", maxLeverage: 20 },
  { symbol: "GOLD", hl: "mkts:GOLD", dex: "mkts", venue: "Markets By Kinetiq", assetClass: "metal", maxLeverage: 25 },
  { symbol: "AAPL", hl: "mkts:AAPL", dex: "mkts", venue: "Markets By Kinetiq", assetClass: "equity", maxLeverage: 15 },
  { symbol: "GOOGL", hl: "mkts:GOOGL", dex: "mkts", venue: "Markets By Kinetiq", assetClass: "equity", maxLeverage: 15 },
  { symbol: "SEMI", hl: "mkts:SEMI", dex: "mkts", venue: "Markets By Kinetiq", assetClass: "equity", maxLeverage: 15 },
  { symbol: "GLDMINE", hl: "mkts:GLDMINE", dex: "mkts", venue: "Markets By Kinetiq", assetClass: "equity", maxLeverage: 10 },
  { symbol: "NVDA", hl: "mkts:NVDA", dex: "mkts", venue: "Markets By Kinetiq", assetClass: "equity", maxLeverage: 12 },
  { symbol: "TENCENT", hl: "mkts:TENCENT", dex: "mkts", venue: "Markets By Kinetiq", assetClass: "equity", maxLeverage: 10 },
  { symbol: "JPN225", hl: "mkts:JPN225", dex: "mkts", venue: "Markets By Kinetiq", assetClass: "equity", maxLeverage: 25 },
  { symbol: "MU", hl: "mkts:MU", dex: "mkts", venue: "Markets By Kinetiq", assetClass: "equity", maxLeverage: 10 },
  { symbol: "PLTR", hl: "mkts:PLTR", dex: "mkts", venue: "Markets By Kinetiq", assetClass: "equity", maxLeverage: 12 },
  { symbol: "XIAOMI", hl: "mkts:XIAOMI", dex: "mkts", venue: "Markets By Kinetiq", assetClass: "equity", maxLeverage: 10 },
  { symbol: "BMNR", hl: "mkts:BMNR", dex: "mkts", venue: "Markets By Kinetiq", assetClass: "equity", maxLeverage: 10 },
  { symbol: "RTX", hl: "mkts:RTX", dex: "mkts", venue: "Markets By Kinetiq", assetClass: "equity", maxLeverage: 10 },
  { symbol: "OAI", hl: "io:OAI", dex: "io", venue: "EntropyIO", assetClass: "crypto", maxLeverage: 6 },
  { symbol: "ANTH", hl: "io:ANTH", dex: "io", venue: "EntropyIO", assetClass: "crypto", maxLeverage: 6 },
  { symbol: "SNDK", hl: "io:SNDK", dex: "io", venue: "EntropyIO", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "IONQ", hl: "io:IONQ", dex: "io", venue: "EntropyIO", assetClass: "crypto", maxLeverage: 20 },
  { symbol: "NBIS", hl: "io:NBIS", dex: "io", venue: "EntropyIO", assetClass: "crypto", maxLeverage: 10 },
  { symbol: "EWY", hl: "io:EWY", dex: "io", venue: "EntropyIO", assetClass: "index", maxLeverage: 20 },
  { symbol: "GPRO", hl: "io:GPRO", dex: "io", venue: "EntropyIO", assetClass: "crypto", maxLeverage: 5 },
];

const BY_HL = new Map(HL_UNIVERSE.map((a) => [a.hl.toUpperCase(), a]));

export const FEATURED_SYMBOLS = [
  "BTC",
  "ETH",
  "SOL",
  "HYPE",
  "SP500",
  "CL",
  "GOLD",
  "NVDA",
  "TSLA",
  "AAPL",
  "EUR",
  "XRP",
] as const;

export function findHlAsset(q: string | undefined | null): HlAsset | undefined {
  if (!q) return undefined;
  const k = q.trim().toUpperCase();
  const byHl = BY_HL.get(k);
  if (byHl) return byHl;
  for (const a of HL_UNIVERSE) {
    if (a.symbol.toUpperCase() === k) return a;
  }
  return undefined;
}

export function searchHlAssets(q: string, limit = 50, venue: VenueFilter = "all"): HlAsset[] {
  const k = q.trim().toUpperCase();
  const pool = HL_UNIVERSE.filter((a) => inVenue(a, venue));
  if (!k) {
    const featured: HlAsset[] = [];
    const seen = new Set<string>();
    for (const s of FEATURED_SYMBOLS) {
      const a = pool.find((x) => x.symbol === s) ?? (venue === "all" ? findHlAsset(s) : undefined);
      if (a && inVenue(a, venue) && !seen.has(a.hl)) {
        seen.add(a.hl);
        featured.push(a);
      }
    }
    for (const a of pool) {
      if (featured.length >= limit) break;
      if (seen.has(a.hl)) continue;
      seen.add(a.hl);
      featured.push(a);
    }
    return featured.slice(0, limit);
  }

  const scored: { a: HlAsset; score: number }[] = [];
  for (const a of pool) {
    const sym = a.symbol.toUpperCase();
    const hl = a.hl.toUpperCase();
    const ticker = hl.includes(":") ? hl.slice(hl.indexOf(":") + 1) : hl;
    let score = 0;
    if (sym === k || hl === k || ticker === k) score = 100;
    else if (sym.startsWith(k) || ticker.startsWith(k)) score = 80;
    else if (hl.startsWith(k)) score = 70;
    else if (sym.includes(k) || ticker.includes(k)) score = 40;
    else if (
      hl.includes(k) ||
      a.venue.toUpperCase().includes(k) ||
      a.assetClass.toUpperCase().startsWith(k) ||
      a.dex.toUpperCase() === k
    ) {
      score = 20;
    }
    if (score) scored.push({ a, score });
  }
  scored.sort((x, y) => y.score - x.score || x.a.symbol.localeCompare(y.a.symbol) || x.a.dex.localeCompare(y.a.dex));
  return scored.slice(0, limit).map((s) => s.a);
}

export const HL_COUNT = HL_UNIVERSE.length;
export const HL_SYMBOLS: readonly string[] = HL_UNIVERSE.map((a) => a.symbol);
export const HL_NATIVE = HL_UNIVERSE.filter((a) => a.dex === "native");
export const XYZ_UNIVERSE = HL_UNIVERSE.filter((a) => a.dex === "xyz");
export const HL_NATIVE_COUNT = HL_NATIVE.length;
export const XYZ_COUNT = XYZ_UNIVERSE.length;

export type VenueFilter = "all" | "hl" | "xyz";

export function venueOf(a: HlAsset): VenueFilter {
  return a.dex === "xyz" ? "xyz" : a.dex === "native" ? "hl" : "all";
}

export function inVenue(a: HlAsset, venue: VenueFilter): boolean {
  if (venue === "all") return true;
  if (venue === "hl") return a.dex === "native";
  return a.dex === "xyz";
}

